import social_core.exceptions


class AuthFailedMissingReturnValues(social_core.exceptions.AuthException):
    pass
